### ISSUE TITLE
Segmentation fault when running robpath.py

### ISSUE THREAD

**Issue by NatholBMX** [openlmd/robpath#6]
Traceback:

Starting program: /usr/bin/python robpath.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd9bae700 (LWP 25730)]
[New Thread 0x7fffd93ad700 (LWP 25731)]
[New Thread 0x7fffd8bac700 (LWP 25732)]
[New Thread 0x7fffcb928700 (LWP 25733)]
[New Thread 0x7fffcb127700 (LWP 25734)]
[Thread 0x7fffcb127700 (LWP 25734) exited]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fff724bffec in QBasicAtomicInt::ref() ()
   from /usr/lib/x86_64-linux-gnu/qt4/plugins/accessiblebridge/libqspiaccessiblebridge.so
(gdb) backtrace
#0  0x00007fff724bffec in QBasicAtomicInt::ref() ()
   from /usr/lib/x86_64-linux-gnu/qt4/plugins/accessiblebridge/libqspiaccessiblebridge.so
#1  0x00007fff724cd05b in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt4/plugins/accessiblebridge/libqspiaccessiblebridge.so
#2  0x00007fff724cce30 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt4/plugins/accessiblebridge/libqspiaccessiblebridge.so
#3  0x00007fff724cce60 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt4/plugins/accessiblebridge/libqspiaccessiblebridge.so
#4  0x00007ffff7de74ea in call_init (l=<optimized out>, argc=argc@entry=2, 
    argv=argv@entry=0x7fffffffdb58, env=env@entry=0xd5b560) at dl-init.c:72
#5  0x00007ffff7de75fb in call_init (env=0xd5b560, argv=0x7fffffffdb58, 
    argc=2, l=<optimized out>) at dl-init.c:30
#6  _dl_init (main_map=main_map@entry=0x2a915c0, argc=2, argv=0x7fffffffdb58, 
    env=0xd5b560) at dl-init.c:120
#7  0x00007ffff7dec712 in dl_open_worker (a=a@entry=0x7fffffffb080)
    at dl-open.c:575
#8  0x00007ffff7de7394 in _dl_catch_error (
    objname=objname@entry=0x7fffffffb070, 
    errstring=errstring@entry=0x7fffffffb078,

**Comment by blodeiro** [comment]
I cannot reproduce the error. You can try to run the new version released (0.6.0) at master branch, and comment if the same error persists.
